name: Generate Docs
on:
  push:
    branches:
      - master
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
    - name: Generate Documentation for each file
      run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file > temp_dashboard.json
            rastogiji/grafana-autodoc@main --dashboard temp_dashboard.json
          done
    - name: Get MD file
      run: |
          
