name: Generate Docs
on:
  push:
    branches:
      - master
    paths:
      - '**/*.json'
jobs:
  get-changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        json: true
        quotepath: false
    - name: 'Set output in the matrix format'
      id: set-output
      run: echo "changed_files={\"files\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"
  doc:
    runs-on: ubuntu-latest
    needs:
    - get-changes
    strategy:
      matrix: ${{fromJson(needs.get-changes.outputs.changed_files)}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: generate doc
      uses: rastogiji/grafana-autodoc@main
      with:
        dashboard: ${{ matrix.files }}
    
