name: Generate Docs
on:
  push:
      branches:
        - master
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
    - name: List all changed files
      run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
    - name: Generate Documentation
      uses: rastogiji/grafana-autodoc@f595a7a9f2d2573be5e2f8f533bfba9ce092abf3
      with:
        dashboard: "test.json"
