name: Generate Docs
on:
  push:
    branches:
      - master
    paths:
      - '**/*.json'
jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-output.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          quotepath: false
      - name: Set output in the matrix format
        id: set-output
        run: |
          JSON=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | jq -c '{files: .}')
          echo "matrix=$JSON" >> $GITHUB_OUTPUT
          echo "$GITHUB_OUTPUT"

  doc:
    runs-on: ubuntu-latest
    needs: get-changes
    strategy:
      matrix:
        file: ${{ fromJson(needs.get-changes.outputs.matrix).files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print Outputs
        run: |
          echo "$GITHUB_OUTPUT"
      - name: Generate Documentation
        uses: rastogiji/grafana-autodoc@main
        with:
          dashboard: ${{ matrix.file }}
      - name: Get MD file
        run: |
          ls -la
